### ISSUE TITLE
require selectize.default isn't properly working

### ISSUE THREAD

**Issue by lebart** [manuelvanrijn/selectize-rails#11]
Hi, 

A strange thing happens, I required as mention in your doc the selectize and selectize.default in my application.sass file. But the default theme was never applied. If I analyze the source of my page, the file isn't present but no errors is present. I can even require selectize or just selectize.default in my application.sass and I get the same output like if selectize.default was just selectize.css. 

If I copy an past the code in your repo (selectize.default) in a sass file (after conversion of course) the theme 

The other themes are working as expected.

Any idea where this can comes from?

**Comment by manuelvanrijn** [comment]
Hi @lebart. Do you still have this problem? I've just released a scss compatible version so it might work now. In case it doesn't do you get any errors or something?

**Comment by manuelvanrijn** [comment]
closing for now. Please repopen is needed
