### ISSUE TITLE
Support SCSS

### ISSUE THREAD

**Issue by jeffreyguenther** [manuelvanrijn/selectize-rails#16]
Would you be interested in a pull request to add scss support to the gem? I think it would be as simple as renaming the css files .scss so they can be required if people would like or `@import`ed into a scss manifest.

**Comment by manuelvanrijn** [comment]
I don't see any problems with that. If you would like to add this that would be great.

p.s. i use https://github.com/manuelvanrijn/selectize-rails/blob/master/update_from_vendor.sh#L11 to update the vendor data so you probably have to change things here

**Comment by jeffreyguenther** [comment]
👍 Ok, I'll work on it. Thanks!

**Comment by JCBoptimumweb** [comment]
Hey @jeffreyguenther, how did you go with this?

**Comment by jeffreyguenther** [comment]
I never got around to it. 😞

**Comment by Genkilabs** [comment]
@jeffreyguenther  If you do this, let us know. I'd rather @import than mix imports and requires.
I'd volunteer... but I know I'll never get around to it either! T_T

**Comment by manuelvanrijn** [comment]
had some time. Added this in version `0.12.4.1`

**Comment by Genkilabs** [comment]
Awesome! thanks.
