### ISSUE TITLE
Fix an issue in selectize upstream

### ISSUE THREAD

**Issue by lfdominguez** [manuelvanrijn/selectize-rails#17]
Hello, @dairondv1986 made a pull request to fix an issue with the lib, but the CI of main selectize repo is wrong and seem that the developer dont see the pull request. I was applied the solution and works great, please merge with this gem
https://github.com/selectize/selectize.js/pull/1367/commits/527fe65a030661a497ed6aa2a4884a6ad1f1a612

The main problem is when we need to initial set a value into selectize component this put "undefined".

**Comment by manuelvanrijn** [comment]
Sorry I wan't this gem to only contain the code as it's provided by selectize. Please make a fork if you really need this and aren't able to get the feature merged in the selectize.js project
