### ISSUE TITLE
Bump to Selectize 0.12.6

### ISSUE THREAD

**Issue by mbennie** [manuelvanrijn/selectize-rails#20]
It looks like Selectize is at 12.6 now (with a fix for tabbing in Firefox that I'm trying to resolve). Could you bump the version? I can do a PR if that is helpful.

**Comment by manuelvanrijn** [comment]
just run the script to check for updates, but it doesn't seem that there are any changes in the code?
If I missed something, please create a PR :)

**Comment by mbennie** [comment]
You are correct - apologies, it appears the change I was looking at did not make it into 12.6
