### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mixin' of undefined

### ISSUE THREAD

**Issue by gottfrois** [manuelvanrijn/selectize-rails#8]
I'm seeing this error while using `selectize-rails-0.12.0`. After looking around it seems it's because we need to use the standalone version of selectize. Any idea how to solve this ?

Thx.

**Comment by manuelvanrijn** [comment]
that's weird because the included javascript is the standalone version. see: https://github.com/manuelvanrijn/selectize-rails/blob/master/update_from_vendor.sh#L11

Could be some other issue?

**Comment by gottfrois** [comment]
yes thx for looking at it, it was coming from elsewhere

**Comment by eugeneidan** [comment]
@gottfrois where was it coming from?? Can you paste what you found here.
